//! Python modules reached through interfaces (R27, adr:0012): their functions are typed like
//! lotml's own, and each returns `T ! PyError`.

use lotml_check::{Interfaces, check_resolved_with, interface};
use lotml_syntax::parse;

const TEXTWRAP: &str = "\
# Generated by `lotml bind textwrap`.
fn dedent(text: str) -> str ! PyError
fn wrap(text: str, width: int = 70) -> [str] ! PyError
fn shorten(text: str, width: int) -> str ! PyError
";

fn interfaces() -> Interfaces {
    let (textwrap, problems) = interface(TEXTWRAP);
    assert!(problems.is_empty(), "{:?}", problems.iter().map(|d| &d.message).collect::<Vec<_>>());
    Interfaces::from([("textwrap".to_string(), textwrap)])
}

fn codes(source: &str) -> Vec<&'static str> {
    check_resolved_with(&parse(source).module, source, &interfaces()).diagnostics.iter().map(|d| d.code).collect()
}

fn clean(source: &str) {
    let found = check_resolved_with(&parse(source).module, source, &interfaces()).diagnostics;
    assert!(found.is_empty(), "{source}\n{:?}", found.iter().map(|d| (d.code, &d.message)).collect::<Vec<_>>());
}

#[test]
fn an_interface_declares_signatures_that_return_py_error() {
    let (read, problems) = interface(TEXTWRAP);
    assert!(problems.is_empty());
    assert_eq!(read.names().collect::<Vec<_>>(), vec!["dedent", "shorten", "wrap"]);
}

#[test]
fn an_interface_holds_nothing_else() {
    let code = |text: &str| interface(text).1.iter().map(|d| d.code).collect::<Vec<_>>();
    assert_eq!(code("fn f(x: int) -> int\n"), vec!["E0221"], "a function that cannot fail");
    assert_eq!(code("fn f(x: int) -> int ! PyError:\n    return x\n"), vec!["E0221"], "a body");
    assert_eq!(code("fn f[T](x: T) -> T ! PyError\n"), vec!["E0221"], "type parameters");
    assert_eq!(code("type P(x: int)\n"), vec!["E0221"]);
    assert_eq!(code("fn f(x: Widget) -> int ! PyError\n"), vec!["E0202"], "a type nobody declared");
    let (kept, problems) = interface("fn f(x: Widget) -> int ! PyError\nfn g() -> int ! PyError\n");
    assert_eq!(problems.len(), 1);
    assert_eq!(kept.names().collect::<Vec<_>>(), vec!["g"], "a wrong function is left out, the rest stay");
}

#[test]
fn an_imported_function_is_called_like_a_lotml_one() {
    clean(
        "from textwrap import dedent, wrap\n\nfn f(s: str) -> [str] ! PyError:\n    t = dedent(s)?\n    return wrap(t, width=20)?\n",
    );
    clean("from textwrap import wrap\n\nfn f(s: str) -> [str] ! PyError:\n    return wrap(s)?\n");
    clean("import textwrap\n\nfn f(s: str) -> str ! PyError:\n    return textwrap.shorten(s, 10)?\n");
}

#[test]
fn every_call_into_python_can_fail() {
    assert_eq!(codes("from textwrap import dedent\n\nfn f(s: str) -> str:\n    return dedent(s)\n"), vec!["E0219"]);
    clean(
        "from textwrap import dedent\n\nfn f(s: str) -> str:\n    match dedent(s):\n        case Ok(t):\n            return t\n        case Err(e):\n            return e.kind + \": \" + e.message\n",
    );
}

#[test]
fn a_function_or_module_without_an_interface_is_reported() {
    assert_eq!(codes("from textwrap import fill\n\nfn f() -> int:\n    return 1\n"), vec!["E0216"]);
    assert_eq!(
        codes("import textwrap\n\nfn f(s: str) -> str ! PyError:\n    return textwrap.fill(s)?\n"),
        vec!["E0205"]
    );
    let source = "import json\n\nfn f() -> int:\n    return 1\n";
    let found = check_resolved_with(&parse(source).module, source, &interfaces()).diagnostics;
    assert_eq!(found[0].code, "E0216");
    assert!(found[0].notes.iter().any(|n| n.contains("lotml bind json")), "{:?}", found[0].notes);
}

#[test]
fn an_imported_name_cannot_also_be_declared() {
    assert_eq!(codes("from textwrap import dedent\n\nfn dedent(s: str) -> str:\n    return s\n"), vec!["E0210"]);
}

#[test]
fn a_fallible_function_used_as_a_value_keeps_its_error() {
    clean(
        "type E = Bad\n\nfn parse(s: str) -> int ! E:\n    return s.to_int() ?? fail Bad\n\nfn f() -> int ! E:\n    g = parse\n    return g(\"1\")?\n",
    );
}
