"""Check every generated pilot program; write results.md and results.json."""

import json
from collections import Counter
from pathlib import Path

from check import leaks, parse_error
from semantics import findings

HERE = Path(__file__).parent
RUNS = HERE / "runs"
MAX_BYTES = 256 * 1024


def check_file(variant: str, path: Path) -> dict:
    """Parse error, leaks and semantic findings for one generated program."""
    if path.is_symlink() or path.stat().st_size > MAX_BYTES:
        return {
            "parse_error": "skipped: symlink or larger than 256 KiB",
            "leaks": [],
            "semantics": [],
        }
    source = path.read_text(encoding="utf-8")
    error = parse_error(variant, source)
    result = {"parse_error": error, "leaks": leaks(variant, source), "semantics": []}
    if error is None:
        try:
            result["semantics"] = findings(variant, source)
        except (RecursionError, LookupError, AttributeError, StopIteration) as err:
            result["semantics"] = [("checker error", type(err).__name__)]
    return result


def analyze() -> dict:
    runs = {}
    for run in sorted(p for p in RUNS.iterdir() if p.is_dir()):
        variant = run.name.split("-")[0]
        runs[run.name] = {
            path.stem: check_file(variant, path)
            for path in sorted(run.glob("task-*.x"))
        }
    return runs


def render(runs: dict) -> str:
    out = [
        "# Pilot results",
        "",
        "Generated by `analyze.py` — do not edit by hand.",
        "",
        "## Per run",
        "",
        "| run | programs | parse | no leak | parse and no leak |",
        "| --- | ---: | ---: | ---: | ---: |",
    ]
    for name, files in runs.items():
        n = len(files)
        parsed = sum(f["parse_error"] is None for f in files.values())
        clean = sum(not f["leaks"] for f in files.values())
        both = sum(f["parse_error"] is None and not f["leaks"] for f in files.values())
        out.append(f"| {name} | {n} | {parsed} | {clean} | {both} |")

    out += [
        "",
        "## Leaked constructs, by variant",
        "",
        "| variant | construct | programs |",
    ]
    out.append("| --- | --- | ---: |")
    for variant in ("a", "b"):
        counts = Counter(
            leak
            for name, files in runs.items()
            if name.split("-")[0] == variant
            for f in files.values()
            for leak in f["leaks"]
        )
        for leak, n in counts.most_common():
            out.append(f"| {variant} | `{leak}` | {n} |")

    out += [
        "",
        "## Semantic findings in programs that parse",
        "",
        "| run | task | kind | name |",
        "| --- | --- | --- | --- |",
    ]
    for name, files in runs.items():
        for task, f in files.items():
            for kind, detail in f["semantics"]:
                out.append(f"| {name} | {task} | {kind} | `{detail}` |")

    out += [
        "",
        "## Parse errors",
        "",
        "| run | task | first error |",
        "| --- | --- | --- |",
    ]
    for name, files in runs.items():
        for task, f in files.items():
            if f["parse_error"]:
                message = f["parse_error"].replace("|", "\\|")
                out.append(f"| {name} | {task} | `{message}` |")
    out.append("")
    return "\n".join(out)


def main() -> None:
    runs = analyze()
    (HERE / "results.json").write_text(json.dumps(runs, indent=1), encoding="utf-8")
    (HERE / "results.md").write_text(render(runs), encoding="utf-8")


if __name__ == "__main__":
    main()
