// lotml grammar, variant B, for tree-sitter.
// Generated from harness/lotml_harness/lang/grammar.py; do not edit by hand.
// NEWLINE, INDENT and DEDENT come from src/scanner.c, as Python's tokenizer makes them;
// inside brackets a line break is ignored. Keywords are written in place, so a word is a
// keyword only where the grammar expects one: lotml's keywords are soft.

module.exports = grammar({
  name: 'lotml',
  externals: $ => [$._newline, $._indent, $._dedent],
  extras: $ => [/\r?\n/, /[\t \f]+/, /\\[\t \f]*\r?\n/, $.comment],
  word: $ => $.name,
  rules: {
    source_file: $ => prec.right(repeat($._item)),
    _item: $ => prec.right(choice($.fn_def, $.type_def, $.impl_def, $.trait_def, $.import_stmt, $.test_def)),
    fn_def: $ => prec.right(seq($.fn_head, ':', $.suite)),
    fn_head: $ => prec.right(seq('fn', $.name, optional($.type_params), '(', optional($.params), ')', optional(seq('->', $.ret_type)))),
    trait_def: $ => prec.right(seq('trait', $.name, optional($.type_params), ':', $._newline, $._indent, repeat1($._trait_item), $._dedent)),
    _trait_item: $ => prec.right(choice(seq($.fn_head, $._newline), $.fn_def)),
    impl_def: $ => prec.right(seq('impl', $.type, optional(seq('for', $.type)), ':', $._newline, $._indent, repeat1($.fn_def), $._dedent)),
    test_def: $ => prec.right(seq('test', $.string, ':', $.suite)),
    import_stmt: $ => prec.right(choice(seq('from', $.dotted, 'import', $.name, repeat(seq(',', $.name)), $._newline), seq('import', $.dotted, $._newline))),
    dotted: $ => prec.right(seq($.name, repeat(seq('.', $.name)))),
    type_params: $ => prec.right(seq('[', $.type_param, repeat(seq(',', $.type_param)), ']')),
    type_param: $ => prec.right(seq($.name, optional(seq(':', $.name)))),
    params: $ => prec.right(seq($.param, repeat(seq(',', $.param)), optional(','))),
    param: $ => prec.right(seq(optional(choice('inout', 'sink', 'var')), $.name, optional(seq(':', $.type)), optional(seq('=', $._test)))),
    ret_type: $ => prec.right(seq($.type, optional(seq('!', $.type)))),
    type: $ => prec.right(seq($._base_type, repeat('?'))),
    _base_type: $ => prec.right(choice(seq($.name, optional($.type_args)), seq('[', $.type, ']'), seq('{', $.type, ':', $.type, '}'), seq('{', $.type, '}'), seq('(', $.type, ',', optional(seq($.type, repeat(seq(',', $.type)), optional(','))), ')'), seq('dyn', $.name), 'None')),
    type_args: $ => prec.right(seq('[', $.type, repeat(seq(',', $.type)), ']')),
    type_def: $ => prec.right(choice(seq('type', $.name, optional($.type_params), '(', optional($.fields), ')', $._newline), seq('type', $.name, optional($.type_params), '=', $.variant, repeat(seq('|', $.variant)), $._newline))),
    fields: $ => prec.right(seq($.field, repeat(seq(',', $.field)), optional(','))),
    field: $ => prec.right(seq($.name, ':', $.type, optional(seq('=', $._test)))),
    variant: $ => prec.right(seq($.name, optional(seq('(', optional($.variant_fields), ')')))),
    variant_fields: $ => prec.right(seq($._variant_field, repeat(seq(',', $._variant_field)), optional(','))),
    _variant_field: $ => prec.right(choice($.field, $.type)),
    suite: $ => prec.right(choice($.simple_stmt, seq($._newline, $._indent, repeat1($._stmt), $._dedent))),
    _stmt: $ => prec.right(choice($.simple_stmt, $._compound_stmt)),
    simple_stmt: $ => prec.right(seq($._small_stmt, $._newline)),
    _small_stmt: $ => prec.right(choice($.var_stmt, $.expr_stmt, $.return_stmt, $.assert_stmt, $.pass_stmt, $.break_stmt, $.continue_stmt)),
    var_stmt: $ => prec.right(seq('var', $.name, optional(seq(':', $.type)), '=', $._testlist)),
    expr_stmt: $ => prec.right(seq($._testlist, optional(choice($.annassign, $.augassign, $.assign)))),
    annassign: $ => prec.right(seq(':', $.type, '=', $._test)),
    assign: $ => prec.right(seq('=', $._testlist)),
    augassign: $ => prec.right(seq($.augop, $._test)),
    return_stmt: $ => prec.right(seq('return', optional($._testlist))),
    assert_stmt: $ => prec.right(seq('assert', $._test, optional(seq(',', $._test)))),
    pass_stmt: $ => prec.right('pass'),
    break_stmt: $ => prec.right('break'),
    continue_stmt: $ => prec.right('continue'),
    _compound_stmt: $ => prec.right(choice($.if_stmt, $.while_stmt, $.for_stmt, $.match_stmt)),
    if_stmt: $ => prec.right(seq('if', $._test, ':', $.suite, repeat($.elif_clause), optional($.else_clause))),
    elif_clause: $ => prec.right(seq('elif', $._test, ':', $.suite)),
    else_clause: $ => prec.right(seq('else', ':', $.suite)),
    while_stmt: $ => prec.right(seq('while', $._test, ':', $.suite)),
    for_stmt: $ => prec.right(seq('for', $.targets, 'in', $._testlist, ':', $.suite)),
    targets: $ => prec.right(seq($._target, repeat(seq(',', $._target)))),
    _target: $ => prec.right(choice($.name, seq('(', $.targets, ')'))),
    match_stmt: $ => prec.right(seq('match', $._test, ':', $._newline, $._indent, repeat1($.arm), $._dedent)),
    arm: $ => prec.right(seq('case', $.pattern, ':', $.suite)),
    pattern: $ => prec.right(choice(seq($.name, '(', optional(seq($.pattern, repeat(seq(',', $.pattern)))), ')'), $.name, seq('(', $.pattern, ',', optional(seq($.pattern, repeat(seq(',', $.pattern)))), ')'), $.literal)),
    literal: $ => prec.right(choice(seq(optional(choice('+', '-')), $.number), $.string, 'True', 'False', 'None')),
    _testlist: $ => prec.right(seq($._test, repeat(seq(',', $._test)))),
    _test: $ => prec.right(choice(seq($._coalesce, optional(seq('if', $._coalesce, 'else', $._test))), $.lambdef)),
    lambdef: $ => prec.right(seq('lambda', optional(seq($.name, repeat(seq(',', $.name)))), ':', $._test)),
    _coalesce: $ => prec.right(seq($._or_test, repeat(seq('??', $._or_test)))),
    _or_test: $ => prec.right(seq($._and_test, repeat(seq('or', $._and_test)))),
    _and_test: $ => prec.right(seq($._not_test, repeat(seq('and', $._not_test)))),
    _not_test: $ => prec.right(choice(seq('not', $._not_test), $._comparison_rule)),
    _comparison_rule: $ => prec.right(seq($._bit_or, repeat(seq($.comp_op, $._bit_or)))),
    comp_op: $ => prec.right(choice($._comparison, 'in', seq('not', 'in'), 'is', seq('is', 'not'))),
    _bit_or: $ => prec.right(seq($._bit_xor, repeat(seq('|', $._bit_xor)))),
    _bit_xor: $ => prec.right(seq($._bit_and, repeat(seq('^', $._bit_and)))),
    _bit_and: $ => prec.right(seq($._shift_rule, repeat(seq('&', $._shift_rule)))),
    _shift_rule: $ => prec.right(seq($._arith, repeat(seq($._shift, $._arith)))),
    _arith: $ => prec.right(seq($._term, repeat(seq($._sign, $._term)))),
    _term: $ => prec.right(seq($._factor, repeat(seq($._product, $._factor)))),
    _factor: $ => prec.right(choice(seq($._sign, $._factor), seq('~', $._factor), $._power)),
    _power: $ => prec.right(seq($._atom_expr, optional(seq('**', $._factor)))),
    _atom_expr: $ => prec.right(choice(seq($._atom_expr, '(', optional($.arguments), ')'), seq($._atom_expr, '[', $._subscript, ']'), seq($._atom_expr, '.', $.name), seq($._atom_expr, '?'), $._atom)),
    arguments: $ => prec.right(seq($.argument, repeat(seq(',', $.argument)), optional(','))),
    argument: $ => prec.right(choice(seq($.name, '=', $._test), seq('&', $._atom_expr), seq($._test, optional($.comp_for)))),
    _subscript: $ => prec.right(choice($._test, seq(optional($._test), ':', optional($._test), optional(seq(':', optional($._test)))))),
    _atom: $ => prec.right(choice($.name, $.number, repeat1($.string), 'True', 'False', 'None', seq('(', ')'), seq('(', $._test, ')'), seq('(', $._test, ',', optional(seq($._test, repeat(seq(',', $._test)), optional(','))), ')'), seq('(', $._test, $.comp_for, ')'), seq('[', optional(seq($._test, repeat(seq(',', $._test)), optional(','))), ']'), seq('[', $._test, $.comp_for, ']'), seq('{', optional(seq($.dict_item, repeat(seq(',', $.dict_item)), optional(','))), '}'), seq('{', $.dict_item, $.comp_for, '}'), seq('{', $._test, repeat(seq(',', $._test)), optional(','), '}'), seq('{', $._test, $.comp_for, '}'), seq('fail', $._atom_expr))),
    dict_item: $ => prec.right(seq($._test, ':', $._test)),
    comp_for: $ => prec.right(seq('for', $.targets, 'in', $._or_test, repeat(seq('if', $._or_test)), optional($.comp_for))),
    _comparison: $ => prec.right(choice('<', '>', '==', '!=', '<=', '>=')),
    _shift: $ => prec.right(choice('<<', '>>')),
    _sign: $ => prec.right(choice('+', '-')),
    _product: $ => prec.right(choice('*', '/', '//', '%')),
    augop: $ => token(choice('+=', '-=', '*=', '/=', '//=', '%=', '**=', '&=', '|=', '^=', '<<=', '>>=')),
    name: $ => token(/[A-Za-z_][A-Za-z0-9_]*/),
    number: $ => token(/0[xX][0-9a-fA-F_]+|0[bB][01_]+|0[oO][0-7_]+|\d[\d_]*(\.\d[\d_]*)?([eE][+-]?\d+)?/),
    string: $ => token(/[rRbBfF]{0,2}("""(("|"")?([^"\\]|\\(.|\n)))*"""|'''(('|'')?([^'\\]|\\(.|\n)))*'''|"([^"\\\n]|\\(.|\n))*"|'([^'\\\n]|\\(.|\n))*')/),
    comment: $ => token(/#[^\n]*/),
  },
});
