"""Check that every quoted claim appears verbatim in its downloaded source.

Run `fetch.py` first; this writes `results.md` and `results.json` and exits 1 when a quote is
missing from its source.
"""

import json
import re
import sys
import unicodedata
from pathlib import Path

HERE = Path(__file__).parent
CACHE = HERE / "cache"

# A canonical quote shorter than this could match by accident, even within one paper.
MIN_QUOTE = 12

_FOLD = str.maketrans({"’": "'", "‘": "'", "“": '"', "”": '"', "−": "-", "–": "-"})
# Signs and comparisons count only next to a digit: `-5`, `10-20`, `p<0.05`.
_DROP = re.compile(r"(?<!\d)[-+<>=≤≥](?!\d)|[^\w.%@+\-<>=≤≥]|_")


def canonical(text: str) -> str:
    """Fold layout differences away: ligatures, case, line-break hyphens, punctuation.

    Whatever sits next to a number survives, so a quote cannot match a paper whose number
    has the opposite sign or comparison.
    """
    text = unicodedata.normalize("NFKC", text).translate(_FOLD).lower()
    text = re.sub(r"-\s*\n\s*", "", text)
    text = re.sub(r"\s+", "", text)
    return _DROP.sub("", text)


def find_quote(pages: list[str], quote: str) -> int | None:
    """Return the 1-based page where `quote` starts, or None; quotes may cross pages."""
    starts, joined = [], ""
    for page in pages:
        starts.append(len(joined))
        joined += canonical(page)
    at = joined.find(canonical(quote))
    if at < 0:
        return None
    return max(i for i, start in enumerate(starts) if start <= at) + 1


SOURCE_ID = re.compile(r"[A-Za-z0-9][A-Za-z0-9._-]*")


def check_source(source: dict) -> None:
    """A source id becomes a file name in `cache/`, and only https is fetched."""
    if not SOURCE_ID.fullmatch(source["id"]):
        raise ValueError(f"source id {source['id']!r} is not a plain file name")
    if not source["url"].startswith("https://"):
        raise ValueError(f"source {source['id']!r} is not fetched over https")


def load_sources(path: Path) -> dict[str, dict]:
    sources = json.loads(path.read_text("utf-8"))
    for source in sources:
        check_source(source)
    return {source["id"]: source for source in sources}


def load_claims(path: Path, sources_path: Path) -> list[dict]:
    """Read the claims, rejecting unknown sources and quotes too short to be decisive."""
    sources = load_sources(sources_path)
    claims = json.loads(path.read_text("utf-8"))
    for claim in claims:
        if claim["source"] not in sources:
            raise ValueError(f"unknown source {claim['source']!r}")
        if len(canonical(claim["quote"])) < MIN_QUOTE:
            raise ValueError(f"quote shorter than {MIN_QUOTE}: {claim['quote']!r}")
    return claims


def pages_of(source_id: str) -> list[str]:
    path = CACHE / f"{source_id}.pages.json"
    if not path.exists():
        raise FileNotFoundError(f"{path.name} missing: run fetch.py")
    return json.loads(path.read_text("utf-8"))


def main() -> int:
    sources = load_sources(HERE / "sources.json")
    claims = load_claims(HERE / "claims.json", HERE / "sources.json")
    rows = []
    for claim in claims:
        page = find_quote(pages_of(claim["source"]), claim["quote"])
        rows.append({**claim, "found_on_page": page})
    missing = [row for row in rows if row["found_on_page"] is None]

    (HERE / "results.json").write_text(
        json.dumps(rows, indent=2, ensure_ascii=False) + "\n", "utf-8"
    )
    lines = [
        "# Claim verification",
        "",
        (
            f"{len(rows) - len(missing)} of {len(rows)} quotes found verbatim in "
            f"{len({row['source'] for row in rows})} sources. Generated by `verify.py`."
        ),
        "",
        "| claim | source | page | quote |",
        "| --- | --- | ---: | --- |",
    ]
    for row in rows:
        title = sources[row["source"]].get("title", row["source"])
        page = row["found_on_page"] or "**missing**"
        quote = row["quote"].replace("|", "\\|")
        lines.append(
            f"| {row['claim']} | {row['source']} — {title} | {page} | {quote} |"
        )
    (HERE / "results.md").write_text("\n".join(lines) + "\n", "utf-8")

    for row in missing:
        print(f"missing: {row['source']}: {row['quote']}", file=sys.stderr)
    print(f"{len(rows) - len(missing)}/{len(rows)} quotes found")
    return 1 if missing else 0


if __name__ == "__main__":
    sys.exit(main())
